= Υπολογιστική Νέφους και Υπηρεσίες

.ΕΡΓΑΣΤΗΡΙΟ ΜΑΘΗΜΑΤΟΣ
[ΝΟΤΕ]
*****
[.text-center]
ΆΣΚΗΣΗ 2021

Το project που αναλάβαμε και αναλύεται παρακάτω περιλαμβάνει την ανάπτυξη μιας πλήρης διαδικτυακής εφαρμογής για ένα E-Shop ηλεκτρονικών παιχνιδιών με βάση την ανάθεση *3.1 Data Collector service*.
*****


Ιάκωβος Μαστρογιαννόπουλος - cse242017102 +
Μάριος-Σταμάτης Κατσαρός - cse242017011 +
Ρούσου Αντρέι - cs171075 +

== Εισαγωγή
=== Περιγραφή
Η ανάπτυξη του back-end της εφαρμογής έγινε με χρήση του https://flask.palletsprojects.com/en/2.0.x/[*Flask*], ένα Python framework για την δημιουργία RESTful APIs. Η ανάπτυξη του front-end της εφαρμογής έγινε με https://vuejs.org/[*Vue.js*], JavaScript framework για την δημιουργία του UI της εφαρμογής. Η εφαρμογή μας τρέχει πάνω στη πλατφόρμα ανάπτυξης λογισμικού https://nodejs.org/en/[*Node.js*]. Η διαχείριση των δεδομένων, όπως των βάσεων δεδομένων των παιχνιδιών του E-SHOP αλλά και δεδομένα των χρηστών, γίνεται μέσω https://www.mongodb.com/1[*MongoDB*]. Για εύκολη διαχείριση γίνεται και χρήση της https://github.com/mongo-express/mongo-express[*mongo-express*] που είναι web-based MongoDB admin interface. Η σύνδεση με τη βάση γίνεται μέ την χρήση της βιβλιοθήκης https://pymongo.readthedocs.io/en/stable/[*pymongo*]. Συλλογή δεδομένων και συγκεκριμένα logs γίνεται με την χρήση του https://www.fluentd.org/[*Fluentd*]. Η εφαρμογή είναι πλήρως dockerized και όλες οι υπηρεσίες τρέχουν σε https://www.docker.com/[*Docker*] containers.

=== Εγκατάσταση
Κάνουμε clone από το repo με την παρακάτω εντολή:

```
git clone https://github.com/IakMastro/Cloud-Eshop-Project-2021
```
Και έπειτα κάνουμε deploy με την εντολή:

```
docker-compose up --build --force-recreate
```

NOTE: Πρέπει να έχει γίνει σωστά η εγκατάσταση του *Docker* και *docker-compose*. Οδηγίες σχετικά με την εγκατάσταση http://docs.swarmlab.io/SwarmLab-HowTos/labs/Howtos/docker/install.adoc.html[εδώ].

== Ενότητα Πρώτη
=== Δημιουργία δικτύου

=== Αυτόματη εγκατάσταση προγράμματος για την συλλογή των δεδομένων

=== Αυτόματη εγκατάσταση προγράμματος για την συλλογή των δεδομένων

== Ενότητα Δεύτερη
=== Δημιουργία βάσης δεδομένων(Database replication)

=== onEvent αποθήκευση των δεδομένων στην βάση

== Ενότητα Τρίτη
=== Δημιουργία GUI

=== Δημιουργία Websocket σύνδεσης με την βάση ή με τις βασικές υπηρεσίες για άμεση μεταφορά των δεδομένων


