# Yaml compose version
version: "3.8"

# Services used on the swarm
services:
  # Client service
  client:
    # Docker image
    build: client
    # Port forward to 8080
    ports:
      - "8080:8080"
    # Real time developing on this volume
    volumes:
      - ./client:/client
    # NodeJS environment
    environment:
      NODE_APP: client
      NODE_ENV: development

  # Admin service
  admin:
    # Docker image
    build: admin
    # Port forward to 5000 (not permanent, most likely it will change)
    ports:
      - "5000:5000"
    # Real time developing on this volume (hard link, remember from OS1)
    volumes:
      - ./admin:/admin
    # Flask environment
    environment:
      FLASK_APP: admin
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development

  # Users service
  users:
    # Docker image
    build: users
    # Port forward to 5001 (5000 is busy by the admin service)
    ports:
      - "5001:5000"
    # Real time developing on this volume
    volumes:
      - ./users:/users
    # Flask environment
    environment:
      FLASK_APP: users
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development