# Yaml compose version
version: "3.8"

# Services used on the swarm
services:
  # Client service
  client:
    # Docker image
    build: client
    container_name: video-game-store
    # Port forward to 8080
    ports:
      - "8080:8080"
    # Real time developing on this volume
    volumes:
      - ./client:/client
    # NodeJS environment
    environment:
      NODE_APP: client
      NODE_ENV: development
    # Linked containers to client
    links:
      - admin
      - users
      - fluentd
    # Logging driver (loads fluentd container)
    logging:
      driver: "fluentd"
      options:
        # Fluentd address
        fluentd-address: localhost:24224
        # Tag that fluentd sees
        tag: log.client

  # Admin service
  admin:
    # Docker image
    build: admin
    container_name: admin
    # Port forward to 5000
    ports:
      - "5000:5000"
    volumes:
      - ./admin:/admin
    # Flask environment
    environment:
      FLASK_APP: admin
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    links:
      - fluentd
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.admin

  # Users service
  users:
    # Docker image
    build: users
    container_name: users
    # Port forward to 5001 (5000 is busy by the admin service)
    ports:
      - "5001:5000"
    volumes:
      - ./users:/users
    # Flask environment
    environment:
      FLASK_APP: users
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    links:
      - fluentd
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.users

  # Mongo Express service
  # It's a GUI client for MongoDB
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    # User: datinguser
    # Password: datingpasswd
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass
    links:
      - mongo

  # MongoDB service
  mongo:
    build: db
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: gameStore
#    links:
#      - fluentd
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: log.mongo

  # Fluentd service
  fluentd:
    build: logs
    container_name: fluentd
    volumes:
      - ./logs/conf:/fluentd/etc
    # Port forwarded
    ports:
      - "24224:24224"
      - "24224:24224/udp"