# Yaml compose version
version: "3.8"

# Services used on the swarm
services:
  # Client service
  client:
    # Docker image
    build: client
    container_name: video-game-store
    # Port forward to 8080
    ports:
      - "8080:8080"
    # Real time developing on this volume
    volumes:
      - ./client:/client
    # NodeJS environment
    environment:
      NODE_APP: client
      NODE_ENV: development
    # Linked containers to client
    links:
      - admin
      - users
      - fluentd
    # Logging driver (loads fluentd container)
    logging:
      driver: "fluentd"
      options:
        # Fluentd address
        fluentd-address: localhost:24224
        # Tag that fluentd sees
        tag: log.client

  # Admin service
  admin:
    # Docker image
    build: admin
    container_name: admin
    # Port forward to 5000
    ports:
      - "5000:5000"
    volumes:
      - ./admin:/admin
    # Flask environment
    environment:
      FLASK_APP: admin
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    links:
      - fluentd
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.admin

  # Users service
  users:
    # Docker image
    build: users
    container_name: users
    # Port forward to 5001 (5000 is busy by the admin service)
    ports:
      - "5001:5000"
    volumes:
      - ./users:/users
    # Flask environment
    environment:
      FLASK_APP: users
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    links:
      - fluentd
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.users

  # Fluentd service
  fluentd:
    build: logs
    container_name: fluentd
    volumes:
      - ./logs/conf:/fluentd/etc
    # Linked to elasticsearch service
    links:
      - "elasticsearch"
    # Port forwarded
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  # Mongo Express service
  # It's a GUI client for MongoDB
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    # User: datinguser
    # Password: datingpasswd
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: datinguser
      ME_CONFIG_MONGODB_ADMINPASSWORD: datinguserpasswd
    links:
      - mongo

  # MongoDB service
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    # User: datinguser
    # Password: datingpasswd
    environment:
      MONGO_INITDB_ROOT_USERNAME: datinguser
      MONGO_INITDB_ROOT_PASSWORD: datinguserpasswd

  # Kibana service
  kibana:
    image: kibana:7.10.1
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  # Elasticsearch service
  elasticsearch:
    # Pull the image from the web
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"